---
apiVersion: v1
kind: Service
metadata:
    name: capstone-service
spec:
    selector:
        app: blue
    type: LoadBalancer
    ports:
        - protocol: TCP
          targetPort: 80
          port: 80
