---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: green
    labels:
        app: green
    namespace: default
spec:
    replicas: 2
    selector:
        matchLabels:
            app: green
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: green
        spec:
            containers:
                - image: desherbojhaa/udacity-predict
                  imagePullPolicy: Always
                  name: green
                  ports:
                      - containerPort: 80
                        protocol: TCP
                  resources:
                      limits:
                          cpu: "0.5"
                          memory: 200Mi
                      requests:
                          cpu: "0.2"
                          memory: "150"